import { spawn } from "node:child_process";
import fs from "node:fs/promises";
import path from "node:path";
import type { DataSource, OutputFile, MariaDbConfig, CsvConfig, JsonConfig } from "../../shared/types.js";

export function buildDataHelpers(sources: DataSource[]): string {
  const lines: string[] = [
    "import pandas as pd, json, pathlib",
    "",
    "# This file is auto-generated by AidClaude. Do not modify.",
    "# Use these functions to load data from configured sources.",
    "",
  ];

  for (const ds of sources) {
    const safeName = ds.name.replace(/[^a-zA-Z0-9_]/g, "_");

    if (ds.type === "mariadb") {
      const cfg = ds.config as MariaDbConfig;
      lines.push(
        `def load_mariadb_${safeName}(sql: str) -> pd.DataFrame:`,
        `    """Load data from '${ds.name}' (MariaDB ${cfg.database}) using a SELECT query."""`,
        `    import pymysql`,
        `    conn = pymysql.connect(`,
        `        host=${JSON.stringify(cfg.host)},`,
        `        port=${cfg.port},`,
        `        db=${JSON.stringify(cfg.database)},`,
        `        user=${JSON.stringify(cfg.user)},`,
        `        password=${JSON.stringify(cfg.password)},`,
        `        charset="utf8mb4"`,
        `    )`,
        `    try:`,
        `        return pd.read_sql(sql, conn)`,
        `    finally:`,
        `        conn.close()`,
        ``,
      );
    } else if (ds.type === "csv") {
      const cfg = ds.config as CsvConfig;
      const delimArg = cfg.delimiter ? `, sep=${JSON.stringify(cfg.delimiter)}` : "";
      lines.push(
        `def load_csv_${safeName}() -> pd.DataFrame:`,
        `    """Load CSV file: ${ds.name}"""`,
        `    return pd.read_csv(${JSON.stringify(cfg.filePath)}${delimArg})`,
        ``,
      );
    } else if (ds.type === "json") {
      const cfg = ds.config as JsonConfig;
      const rootNav = cfg.rootPath
        ? `\n    for k in ${JSON.stringify(cfg.rootPath.split("."))}: data = data[k]`
        : "";
      lines.push(
        `def load_json_${safeName}():`,
        `    """Load JSON file: ${ds.name}"""`,
        `    data = json.loads(pathlib.Path(${JSON.stringify(cfg.filePath)}).read_text(encoding="utf-8"))${rootNav}`,
        `    return data`,
        ``,
      );
    }
  }

  return lines.join("\n");
}

export interface RunResult {
  exitCode: number;
  stdout: string;
  stderr: string;
  outputFiles: OutputFile[];
}

export async function runAnalysis(
  workspaceDir: string,
  pythonBin: string
): Promise<RunResult> {
  const outputDir = path.join(workspaceDir, "output");
  await fs.mkdir(outputDir, { recursive: true });

  return new Promise((resolve) => {
    let stdout = "";
    let stderr = "";

    const child = spawn(
      pythonBin,
      [path.join(workspaceDir, "analyze.py")],
      {
        cwd: workspaceDir,
        env: { ...process.env, PYTHONPATH: workspaceDir },
        shell: process.platform === "win32",
      }
    );

    child.stdout.on("data", (b: Buffer) => (stdout += b.toString()));
    child.stderr.on("data", (b: Buffer) => (stderr += b.toString()));

    child.on("exit", async (code) => {
      const outputFiles = await scanOutputFiles(outputDir);
      resolve({
        exitCode: code ?? -1,
        stdout,
        stderr,
        outputFiles,
      });
    });

    child.on("error", (err) => {
      resolve({
        exitCode: -1,
        stdout,
        stderr: stderr + `\nFailed to start Python: ${err.message}`,
        outputFiles: [],
      });
    });
  });
}

async function scanOutputFiles(outputDir: string): Promise<OutputFile[]> {
  try {
    const entries = await fs.readdir(outputDir);
    return Promise.all(
      entries
        .filter((name) => !name.startsWith("."))
        .map(async (name) => {
          const fpath = path.join(outputDir, name);
          const stat = await fs.stat(fpath);
          const ext = path.extname(name).toLowerCase();
          const type =
            ext === ".csv" ? "csv"
            : ext === ".png" ? "png"
            : ext === ".html" ? "html"
            : ext === ".json" ? "json"
            : "other";
          return { name, path: fpath, type, sizeBytes: stat.size } satisfies OutputFile;
        })
    );
  } catch {
    return [];
  }
}
