import { spawn } from "node:child_process";
import fs from "node:fs/promises";
import path from "node:path";
import type { OutputFile } from "../../shared/types.js";

/** data_helpers.py — 자격증명 없는 단순 SQLite 래퍼 */
export function buildDataHelpers(tableNames: string[]): string {
  const tableComments = tableNames.map((t) => `# - ${t}`).join("\n");
  return `import sqlite3, pathlib, pandas as pd

# Auto-generated by AidClaude. Do not modify.
_DB = pathlib.Path(__file__).parent / "data.db"


def load(table: str) -> pd.DataFrame:
    """소스 테이블 또는 워킹 테이블을 DataFrame으로 로드합니다."""
    with sqlite3.connect(_DB) as _c:
        return pd.read_sql_query(f'SELECT * FROM "{table}"', _c)


def save(df: pd.DataFrame, table: str, if_exists: str = "replace") -> None:
    """DataFrame을 워킹 테이블로 저장합니다 (if_exists: replace / append)."""
    with sqlite3.connect(_DB) as _c:
        df.to_sql(table, _c, if_exists=if_exists, index=False)


def query(sql: str) -> pd.DataFrame:
    """SQL을 직접 실행합니다 (JOIN, 집계, 서브쿼리 등)."""
    with sqlite3.connect(_DB) as _c:
        return pd.read_sql_query(sql, _c)


def tables() -> list:
    """data.db의 모든 테이블 목록을 반환합니다."""
    with sqlite3.connect(_DB) as _c:
        return [r[0] for r in _c.execute(
            "SELECT name FROM sqlite_master WHERE type='table' ORDER BY name"
        ).fetchall()]


# 사용 가능한 소스 테이블:
${tableComments || "# (없음)"}
`;
}

export interface RunResult {
  exitCode: number;
  stdout: string;
  stderr: string;
  outputFiles: OutputFile[];
}

export async function runAnalysis(
  workspaceDir: string,
  pythonBin: string
): Promise<RunResult> {
  const outputDir = path.join(workspaceDir, "output");
  await fs.mkdir(outputDir, { recursive: true });

  return new Promise((resolve) => {
    let stdout = "";
    let stderr = "";

    const child = spawn(
      pythonBin,
      [path.join(workspaceDir, "analyze.py")],
      {
        cwd: workspaceDir,
        env: { ...process.env, PYTHONPATH: workspaceDir },
        shell: process.platform === "win32",
      }
    );

    child.stdout.on("data", (b: Buffer) => (stdout += b.toString()));
    child.stderr.on("data", (b: Buffer) => (stderr += b.toString()));

    child.on("exit", async (code) => {
      const outputFiles = await scanOutputFiles(outputDir);
      resolve({
        exitCode: code ?? -1,
        stdout,
        stderr,
        outputFiles,
      });
    });

    child.on("error", (err) => {
      resolve({
        exitCode: -1,
        stdout,
        stderr: stderr + `\nFailed to start Python: ${err.message}`,
        outputFiles: [],
      });
    });
  });
}

async function scanOutputFiles(outputDir: string): Promise<OutputFile[]> {
  try {
    const entries = await fs.readdir(outputDir);
    return Promise.all(
      entries
        .filter((name) => !name.startsWith("."))
        .map(async (name) => {
          const fpath = path.join(outputDir, name);
          const stat = await fs.stat(fpath);
          const ext = path.extname(name).toLowerCase();
          const type =
            ext === ".csv" ? "csv"
            : ext === ".png" ? "png"
            : ext === ".html" ? "html"
            : ext === ".json" ? "json"
            : "other";
          return { name, path: fpath, type, sizeBytes: stat.size } satisfies OutputFile;
        })
    );
  } catch {
    return [];
  }
}
