package com.ithows.aida;

import java.util.List;

/**
 * CLAUDE.md(시스템 프롬프트) + data_helpers.py 생성.
 * 기존 system-prompt.ts / python-runner.ts {@code buildDataHelpers} 포팅.
 */
public final class SystemPromptBuilder {

    private SystemPromptBuilder() {}

    public static final class TableInfo {
        public final String tableName;
        public final long rowCount;
        public final String sourceName;
        public TableInfo(String tableName, long rowCount, String sourceName) {
            this.tableName = tableName; this.rowCount = rowCount; this.sourceName = sourceName;
        }
    }

    /** CLAUDE.md 내용. */
    public static String buildClaudeMd(List<TableInfo> tables) {
        StringBuilder list = new StringBuilder();
        if (tables == null || tables.isEmpty()) {
            list.append("  (등록된 소스 없음)");
        } else {
            for (TableInfo t : tables) {
                list.append("  - `").append(t.tableName).append("`  (")
                    .append(String.format("%,d", t.rowCount)).append("행)  ← ")
                    .append(t.sourceName).append("\n");
            }
            if (list.length() > 0) list.setLength(list.length() - 1); // 마지막 개행 제거
        }

        return "You are a SQLite SQL assistant. Read the user's request from request.md and write query.sql.\n"
            + "\n"
            + "## Output format (required)\n"
            + "\n"
            + "Always write 2~3 SQL options separated by option markers:\n"
            + "\n"
            + "```\n"
            + "-- [옵션 1] 옵션 제목\n"
            + "DROP TABLE IF EXISTS result;\n"
            + "CREATE TABLE result AS\n"
            + "SELECT ...;\n"
            + "\n"
            + "-- [옵션 2] 옵션 제목\n"
            + "DROP TABLE IF EXISTS result;\n"
            + "CREATE TABLE result AS\n"
            + "SELECT ...;\n"
            + "```\n"
            + "\n"
            + "Each option must start with `-- [옵션 N]` on its own line.\n"
            + "\n"
            + "## Available tables\n"
            + "\n"
            + list + "\n"
            + "\n"
            + "## Restrictions\n"
            + "\n"
            + "- No INSERT / UPDATE / DELETE / DROP on source tables\n"
            + "- No ATTACH DATABASE or load_extension\n"
            + "- Quote table names containing hyphens: `\"my-table\"`\n"
            + "- **All options MUST write to the same table named `result`** — never use result2, result3, etc.\n"
            + "  Each option must follow this exact pattern:\n"
            + "  `DROP TABLE IF EXISTS result; CREATE TABLE result AS SELECT ...;`\n";
    }

    /** data_helpers.py 내용 (자격증명 없는 sqlite3 래퍼). */
    public static String buildDataHelpers(List<String> tableNames) {
        StringBuilder comments = new StringBuilder();
        if (tableNames == null || tableNames.isEmpty()) {
            comments.append("# (없음)");
        } else {
            for (String t : tableNames) comments.append("# - ").append(t).append("\n");
            comments.setLength(comments.length() - 1);
        }
        return "import sqlite3, pathlib, pandas as pd\n"
            + "\n"
            + "# Auto-generated by AIDA. Do not modify.\n"
            + "_DB = pathlib.Path(__file__).parent / \"data.db\"\n"
            + "\n"
            + "\n"
            + "def load(table: str) -> pd.DataFrame:\n"
            + "    \"\"\"소스 테이블 또는 워킹 테이블을 DataFrame으로 로드합니다.\"\"\"\n"
            + "    with sqlite3.connect(_DB) as _c:\n"
            + "        return pd.read_sql_query(f'SELECT * FROM \"{table}\"', _c)\n"
            + "\n"
            + "\n"
            + "def save(df: pd.DataFrame, table: str, if_exists: str = \"replace\") -> None:\n"
            + "    \"\"\"DataFrame을 워킹 테이블로 저장합니다 (if_exists: replace / append).\"\"\"\n"
            + "    with sqlite3.connect(_DB) as _c:\n"
            + "        df.to_sql(table, _c, if_exists=if_exists, index=False)\n"
            + "\n"
            + "\n"
            + "def query(sql: str) -> pd.DataFrame:\n"
            + "    \"\"\"SQL을 직접 실행합니다 (JOIN, 집계, 서브쿼리 등).\"\"\"\n"
            + "    with sqlite3.connect(_DB) as _c:\n"
            + "        return pd.read_sql_query(sql, _c)\n"
            + "\n"
            + "\n"
            + "def tables() -> list:\n"
            + "    \"\"\"data.db의 모든 테이블 목록을 반환합니다.\"\"\"\n"
            + "    with sqlite3.connect(_DB) as _c:\n"
            + "        return [r[0] for r in _c.execute(\n"
            + "            \"SELECT name FROM sqlite_master WHERE type='table' ORDER BY name\"\n"
            + "        ).fetchall()]\n"
            + "\n"
            + "\n"
            + "# 사용 가능한 소스 테이블:\n"
            + comments + "\n";
    }
}
